
-- 회원 가입할 때 회원번호 시퀀스
CREATE SEQUENCE  "ONE"."MEMBERNO_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- 예약 할때 예약번호 시퀀스
CREATE SEQUENCE  "ONE"."RESERVNO_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;




alter table "ONE"."HALL" rename column "HALLTIME" to "HALLETIME";
ALTER TABLE "ONE"."HALL" ADD HALLSTIME INTEGER;
ALTER TABLE RESERVATION MODIFY RESERVTIME INTEGER;

desc hall;
desc reservation;
select * from member;
select * from reservation;
